// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_bgD1xkCenN8AIDBOPaUlJSf6Mooldw',
    appId: '1:955163893298:web:e80488360f874bea93e62b',
    messagingSenderId: '955163893298',
    projectId: 'postalhub',
    authDomain: 'postalhub.firebaseapp.com',
    databaseURL: 'https://postalhub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'postalhub.appspot.com',
    measurementId: 'G-PGCG1QM2YM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvdIXM1fotfBLeakmBTS_z7E1EulwhD4',
    appId: '1:955163893298:ios:fe7027ba8e1bd91593e62b',
    messagingSenderId: '955163893298',
    projectId: 'postalhub',
    databaseURL: 'https://postalhub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'postalhub.appspot.com',
    iosBundleId: 'com.example.postalhubTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADnzeTel4C2y0vLkcNrSh-FLjffrCtMCs',
    appId: '1:955163893298:android:62a60c72ff83b44d93e62b',
    messagingSenderId: '955163893298',
    projectId: 'postalhub',
    databaseURL: 'https://postalhub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'postalhub.appspot.com',
  );

}